### ISSUE TITLE
download 1.8

### ISSUE THREAD

**Issue by MCG-server** [bergerkiller/TrainCarts#30]
please download 1.8

**Comment by vpontin** [comment]
https://www.spigotmc.org/resources/traincarts.8557/

**Comment by lenis0012** [comment]
I will consider adding 1.8 and 1.9 versions.
but it seems serveral people have already done this.

I don't want to ruin their hard work

**Comment by loftyD** [comment]
lenis0012: Can you point me in the right direction to obtain a 1.8, as I have no idea.

Thanks

**Comment by totoberg123** [comment]
@lenis0012 Is there a possibility to give me the 1.9 version of traincarts?
